const mongoose = require("mongoose");

const costField = {
  type: Number,
  default: 0,
};

const costCurrencyField = {
  type: String,
  default: "",
};

const flightSchema = new mongoose.Schema(
  {
    date: { type: Date },
    day: { type: String },
    flight: { type: String },
    depStn: { type: String },
    std: { type: String },
    bt: { type: String },
    sta: { type: String },
    arrStn: { type: String },
    sector: { type: String },
    variant: { type: String },
    acftType: { type: String },
    ft: { type: String },

    // Numbers
    seats: { type: Number },
    CargoCapT: { type: Number },
    dist: { type: Number },
    pax: { type: Number },
    CargoT: { type: Number },
    ask: { type: Number },
    rsk: { type: Number },
    cargoAtk: { type: Number },
    cargoRtk: { type: Number },
    fh: { type: Number },
    bh: { type: Number },
    engineFuelConsumption: costField,
    engineFuelCost: costField,
    engineFuelCostCCY: costCurrencyField,
    engineFuelCostRCCY: costField,
    maintenanceReserveContribution: costField,
    maintenanceReserveContributionCCY: costCurrencyField,
    maintenanceReserveContributionRCCY: costField,
    mrContribution: costField,
    mrContributionCCY: costCurrencyField,
    mrContributionRCCY: costField,
    transitMaintenance: costField,
    transitMaintenanceCCY: costCurrencyField,
    transitMaintenanceRCCY: costField,
    otherMaintenance: costField,
    otherMaintenanceCCY: costCurrencyField,
    otherMaintenanceRCCY: costField,
    navigation: costField,
    navigationCCY: costCurrencyField,
    navigationRCCY: costField,
    airport: costField,
    airportCCY: costCurrencyField,
    airportRCCY: costField,
    otherDoc: costField,
    otherDocCCY: costCurrencyField,
    otherDocRCCY: costField,
    crewAllowances: costField,
    crewAllowancesCCY: costCurrencyField,
    crewAllowancesRCCY: costField,
    layoverCost: costField,
    layoverCostCCY: costCurrencyField,
    layoverCostRCCY: costField,
    crewPositioningCost: costField,
    crewPositioningCostCCY: costCurrencyField,
    crewPositioningCostRCCY: costField,
    apuFuelCost: costField,
    apuFuelCostCCY: costCurrencyField,
    apuFuelCostRCCY: costField,
    mrMonthly: costField,
    mrMonthlyCCY: costCurrencyField,
    mrMonthlyRCCY: costField,
    qualifyingSchMxEvents: costField,
    qualifyingSchMxEventsCCY: costCurrencyField,
    qualifyingSchMxEventsRCCY: costField,
    otherMxExpenses: costField,
    otherMxExpensesCCY: costCurrencyField,
    otherMxExpensesRCCY: costField,
    rotableChanges: costField,
    rotableChangesCCY: costCurrencyField,
    rotableChangesRCCY: costField,
    otherMaintenance1: costField,
    otherMaintenance2: costField,
    otherMaintenance3: costField,
    navEnr: costField,
    navTrml: costField,
    aptLandingCost: costField,
    aptHandlingCost: costField,
    aptOtherCost: costField,
    otherDoc1: costField,
    otherDoc2: costField,
    otherDoc3: costField,

    domIntl: { type: String },
    userTag1: { type: String },
    userTag2: { type: String },
    remarks1: { type: String },
    remarks2: { type: String },
    sectorId: { type: String },
    networkId: { type: String },
    userId: { type: String },
    isComplete: { type: Boolean },
    rotationNumber: { type: String },
    beyondODs: { type: Boolean, default: false },
    behindODs: { type: Boolean, default: false },
    addedByRotation: { type: String },
    effFromDt: { type: Date },
    effToDt: { type: Date },
    dow: { type: String },
    aircraft: {
      msn: { type: Number, required: false },
      registration: { type: String, required: false }
    },
  }
);

flightSchema.index({ userId: 1, depStn: 1, arrStn: 1, domIntl: 1, std: 1, date: 1 });
flightSchema.index({ userId: 1, date: 1, flight: 1 });
flightSchema.index(
  { userId: 1, networkId: 1, date: 1, flight: 1 },
  {
    unique: true,
    partialFilterExpression: {
      networkId: { $exists: true, $type: "string" },
    },
  }
);
module.exports = mongoose.model("FLIGHT", flightSchema);
