const test = require("node:test");
const assert = require("node:assert/strict");

const pooController = require("../controller/pooController");

const {
    calculateProrateRatio,
    recalculateRevenue,
    buildEditableResponse,
    applyTrafficUpdates,
} = pooController.__testables__;

test("calculates proration from the field-specific ratio before GCD fallback", () => {
    const row = {
        stops: 1,
        sectorGcd: 50,
        odViaGcd: 100,
        fareProrateRatioL1L2: 0.75,
        rateProrateRatioL1L2: 0,
        trafficType: "behind",
    };

    assert.equal(calculateProrateRatio(row, "fareProrateRatioL1L2"), 0.75);
    assert.equal(calculateProrateRatio(row, "rateProrateRatioL1L2"), 0.5);
});

test("uses leg revenue as the OD basis when applySSPricing is enabled", () => {
    const row = recalculateRevenue({
        stops: 0,
        pax: 10,
        cargoT: 5,
        legFare: 1.5,
        legRate: 2,
        odFare: 9,
        odRate: 8,
        fareProrateRatioL1L2: 0,
        rateProrateRatioL1L2: 0,
        pooCcyToRccy: 1,
        applySSPricing: true,
    });

    assert.equal(row.odPaxRev, 15);
    assert.equal(row.odCargoRev, 10);
    assert.equal(row.odTotalRev, 25);
    assert.equal(row.fnlRccyTotalRev, 25);
});

test("buildEditableResponse strips legacy revenue fields from the payload", () => {
    const rows = buildEditableResponse([
        {
            _id: "row-1",
            sNo: 1,
            identifier: "Leg",
            trafficType: "leg",
            poo: "DEL",
            od: "DEL-BOM",
            sector: "DEL-BOM",
            flightNumber: "A100",
            flightId: "flight-1",
            variant: "V1",
            prorateRatioL1: 0.6,
            rccyPax: 1,
            rccyCargo: 2,
            rccyTotalRev: 3,
        },
    ]);

    assert.equal(rows[0].displayType, "Leg");
    assert.equal(rows[0].prorateRatioL1, undefined);
    assert.equal(rows[0].rccyPax, undefined);
    assert.equal(rows[0].rccyCargo, undefined);
    assert.equal(rows[0].rccyTotalRev, undefined);
});

test("rebalances the paired leg when a direct leg is edited", () => {
    const finalRows = applyTrafficUpdates(
        [
            {
                _id: "leg-del",
                trafficType: "leg",
                flightId: "flight-1",
                poo: "DEL",
                od: "DEL-BOM",
                odOrigin: "DEL",
                odDestination: "BOM",
                odDI: "Dom",
                sector: "DEL-BOM",
                legDI: "Dom",
                identifier: "Leg",
                rowKey: "system|leg|DEL|flight-1|none|leg::flight-1",
                odGroupKey: "leg::flight-1",
                pax: 50,
                cargoT: 0,
                maxPax: 100,
                maxCargoT: 10,
                stops: 0,
                sourceSeats: 100,
                sourceCargoCapT: 10,
                sourcePaxLF: 50,
                sourceCargoLF: 0,
                odViaGcd: 1200,
                sectorGcd: 1200,
                totalGcd: 1200,
                legFare: 0,
                legRate: 0,
                odFare: 0,
                odRate: 0,
                fareProrateRatioL1L2: 0,
                rateProrateRatioL1L2: 0,
                pooCcyToRccy: 1,
                applySSPricing: false,
            },
            {
                _id: "leg-bom",
                trafficType: "leg",
                flightId: "flight-1",
                poo: "BOM",
                od: "DEL-BOM",
                odOrigin: "DEL",
                odDestination: "BOM",
                odDI: "Dom",
                sector: "DEL-BOM",
                legDI: "Dom",
                identifier: "Leg",
                rowKey: "system|leg|BOM|flight-1|none|leg::flight-1",
                odGroupKey: "leg::flight-1",
                pax: 50,
                cargoT: 0,
                maxPax: 100,
                maxCargoT: 10,
                stops: 0,
                sourceSeats: 100,
                sourceCargoCapT: 10,
                sourcePaxLF: 50,
                sourceCargoLF: 0,
                odViaGcd: 1200,
                sectorGcd: 1200,
                totalGcd: 1200,
                legFare: 0,
                legRate: 0,
                odFare: 0,
                odRate: 0,
                fareProrateRatioL1L2: 0,
                rateProrateRatioL1L2: 0,
                pooCcyToRccy: 1,
                applySSPricing: false,
            },
        ],
        [{ _id: "leg-del", pax: 55 }]
    );

    const delRow = finalRows.find((row) => row._id === "leg-del");
    const bomRow = finalRows.find((row) => row._id === "leg-bom");

    assert.equal(delRow.pax, 55);
    assert.equal(bomRow.pax, 45);
});

test("rebalance connection traffic across both legs in a two-leg OD", () => {
    const finalRows = applyTrafficUpdates(
        [
            {
                _id: "del-leg",
                trafficType: "leg",
                flightId: "f1",
                poo: "DEL",
                od: "DEL-BOM",
                odOrigin: "DEL",
                odDestination: "BOM",
                odDI: "Dom",
                sector: "DEL-BOM",
                legDI: "Dom",
                identifier: "Leg",
                rowKey: "system|leg|DEL|f1|none|leg::f1",
                odGroupKey: "leg::f1",
                pax: 20,
                cargoT: 2,
                maxPax: 100,
                maxCargoT: 10,
                stops: 0,
                sourceSeats: 100,
                sourceCargoCapT: 10,
                sourcePaxLF: 20,
                sourceCargoLF: 20,
                odViaGcd: 1200,
                sectorGcd: 1200,
                totalGcd: 1200,
                legFare: 0,
                legRate: 0,
                odFare: 0,
                odRate: 0,
                fareProrateRatioL1L2: 0,
                rateProrateRatioL1L2: 0,
                pooCcyToRccy: 1,
                applySSPricing: false,
            },
            {
                _id: "bom-leg",
                trafficType: "leg",
                flightId: "f1",
                poo: "BOM",
                od: "DEL-BOM",
                odOrigin: "DEL",
                odDestination: "BOM",
                odDI: "Dom",
                sector: "DEL-BOM",
                legDI: "Dom",
                identifier: "Leg",
                rowKey: "system|leg|BOM|f1|none|leg::f1",
                odGroupKey: "leg::f1",
                pax: 20,
                cargoT: 2,
                maxPax: 100,
                maxCargoT: 10,
                stops: 0,
                sourceSeats: 100,
                sourceCargoCapT: 10,
                sourcePaxLF: 20,
                sourceCargoLF: 20,
                odViaGcd: 1200,
                sectorGcd: 1200,
                totalGcd: 1200,
                legFare: 0,
                legRate: 0,
                odFare: 0,
                odRate: 0,
                fareProrateRatioL1L2: 0,
                rateProrateRatioL1L2: 0,
                pooCcyToRccy: 1,
                applySSPricing: false,
            },
            {
                _id: "conn-first",
                trafficType: "behind",
                flightId: "f1",
                connectedFlightId: "f2",
                poo: "DEL",
                od: "DEL-MAA",
                odOrigin: "DEL",
                odDestination: "MAA",
                odDI: "Dom",
                sector: "DEL-BOM",
                legDI: "Dom",
                identifier: "Behind",
                rowKey: "system|behind|DEL|f1|f2|system::DEL-MAA::f1::f2",
                odGroupKey: "system::DEL-MAA::f1::f2",
                pax: 0,
                cargoT: 0,
                maxPax: 20,
                maxCargoT: 10,
                stops: 1,
                sourceSeats: 100,
                sourceCargoCapT: 10,
                sourcePaxLF: 20,
                sourceCargoLF: 20,
                odViaGcd: 2400,
                sectorGcd: 1200,
                totalGcd: 2400,
                legFare: 0,
                legRate: 0,
                odFare: 0,
                odRate: 0,
                fareProrateRatioL1L2: 0,
                rateProrateRatioL1L2: 0,
                pooCcyToRccy: 1,
                applySSPricing: false,
            },
            {
                _id: "conn-second",
                trafficType: "beyond",
                flightId: "f2",
                connectedFlightId: "f1",
                poo: "DEL",
                od: "DEL-MAA",
                odOrigin: "DEL",
                odDestination: "MAA",
                odDI: "Dom",
                sector: "BOM-MAA",
                legDI: "Dom",
                identifier: "Beyond",
                rowKey: "system|beyond|DEL|f2|f1|system::DEL-MAA::f1::f2",
                odGroupKey: "system::DEL-MAA::f1::f2",
                pax: 0,
                cargoT: 0,
                maxPax: 20,
                maxCargoT: 10,
                stops: 1,
                sourceSeats: 100,
                sourceCargoCapT: 10,
                sourcePaxLF: 20,
                sourceCargoLF: 20,
                odViaGcd: 2400,
                sectorGcd: 1200,
                totalGcd: 2400,
                legFare: 0,
                legRate: 0,
                odFare: 0,
                odRate: 0,
                fareProrateRatioL1L2: 0,
                rateProrateRatioL1L2: 0,
                pooCcyToRccy: 1,
                applySSPricing: false,
            },
            {
                _id: "maa-leg",
                trafficType: "leg",
                flightId: "f2",
                poo: "MAA",
                od: "BOM-MAA",
                odOrigin: "BOM",
                odDestination: "MAA",
                odDI: "Dom",
                sector: "BOM-MAA",
                legDI: "Dom",
                identifier: "Leg",
                rowKey: "system|leg|MAA|f2|none|leg::f2",
                odGroupKey: "leg::f2",
                pax: 30,
                cargoT: 3,
                maxPax: 100,
                maxCargoT: 10,
                stops: 0,
                sourceSeats: 100,
                sourceCargoCapT: 10,
                sourcePaxLF: 30,
                sourceCargoLF: 30,
                odViaGcd: 1200,
                sectorGcd: 1200,
                totalGcd: 1200,
                legFare: 0,
                legRate: 0,
                odFare: 0,
                odRate: 0,
                fareProrateRatioL1L2: 0,
                rateProrateRatioL1L2: 0,
                pooCcyToRccy: 1,
                applySSPricing: false,
            },
            {
                _id: "bom-leg-f2",
                trafficType: "leg",
                flightId: "f2",
                poo: "BOM",
                od: "BOM-MAA",
                odOrigin: "BOM",
                odDestination: "MAA",
                odDI: "Dom",
                sector: "BOM-MAA",
                legDI: "Dom",
                identifier: "Leg",
                rowKey: "system|leg|BOM|f2|none|leg::f2",
                odGroupKey: "leg::f2",
                pax: 30,
                cargoT: 3,
                maxPax: 100,
                maxCargoT: 10,
                stops: 0,
                sourceSeats: 100,
                sourceCargoCapT: 10,
                sourcePaxLF: 30,
                sourceCargoLF: 30,
                odViaGcd: 1200,
                sectorGcd: 1200,
                totalGcd: 1200,
                legFare: 0,
                legRate: 0,
                odFare: 0,
                odRate: 0,
                fareProrateRatioL1L2: 0,
                rateProrateRatioL1L2: 0,
                pooCcyToRccy: 1,
                applySSPricing: false,
            },
        ],
        [{ _id: "conn-first", pax: 5, cargoT: 1 }]
    );

    assert.equal(finalRows.find((row) => row._id === "conn-first").pax, 5);
    assert.equal(finalRows.find((row) => row._id === "conn-second").pax, 5);
    assert.equal(finalRows.find((row) => row._id === "del-leg").pax, 15);
    assert.equal(finalRows.find((row) => row._id === "maa-leg").pax, 25);
});

test("rejects an edit when the balancing bucket does not have enough capacity", () => {
    assert.throws(() =>
        applyTrafficUpdates(
            [
                {
                    _id: "leg-del",
                    trafficType: "leg",
                    flightId: "flight-1",
                    poo: "DEL",
                    od: "DEL-BOM",
                    odOrigin: "DEL",
                    odDestination: "BOM",
                    odDI: "Dom",
                    sector: "DEL-BOM",
                    legDI: "Dom",
                    identifier: "Leg",
                    rowKey: "system|leg|DEL|flight-1|none|leg::flight-1",
                    odGroupKey: "leg::flight-1",
                    pax: 50,
                    cargoT: 0,
                    maxPax: 100,
                    maxCargoT: 10,
                    stops: 0,
                    sourceSeats: 100,
                    sourceCargoCapT: 10,
                    sourcePaxLF: 50,
                    sourceCargoLF: 0,
                    odViaGcd: 1200,
                    sectorGcd: 1200,
                    totalGcd: 1200,
                    legFare: 0,
                    legRate: 0,
                    odFare: 0,
                    odRate: 0,
                    fareProrateRatioL1L2: 0,
                    rateProrateRatioL1L2: 0,
                    pooCcyToRccy: 1,
                    applySSPricing: false,
                },
                {
                    _id: "leg-bom",
                    trafficType: "leg",
                    flightId: "flight-1",
                    poo: "BOM",
                    od: "DEL-BOM",
                    odOrigin: "DEL",
                    odDestination: "BOM",
                    odDI: "Dom",
                    sector: "DEL-BOM",
                    legDI: "Dom",
                    identifier: "Leg",
                    rowKey: "system|leg|BOM|flight-1|none|leg::flight-1",
                    odGroupKey: "leg::flight-1",
                    pax: 0,
                    cargoT: 0,
                    maxPax: 100,
                    maxCargoT: 10,
                    stops: 0,
                    sourceSeats: 100,
                    sourceCargoCapT: 10,
                    sourcePaxLF: 0,
                    sourceCargoLF: 0,
                    odViaGcd: 1200,
                    sectorGcd: 1200,
                    totalGcd: 1200,
                    legFare: 0,
                    legRate: 0,
                    odFare: 0,
                    odRate: 0,
                    fareProrateRatioL1L2: 0,
                    rateProrateRatioL1L2: 0,
                    pooCcyToRccy: 1,
                    applySSPricing: false,
                },
            ],
            [{ _id: "leg-del", pax: 60 }]
        )
    );
});

test("applies the 4 Mar DEL POO example across leg, behind, and beyond rows", () => {
    const baseRow = (overrides) => ({
        _id: overrides._id,
        trafficType: overrides.trafficType,
        flightId: overrides.flightId,
        connectedFlightId: overrides.connectedFlightId || null,
        poo: overrides.poo,
        od: overrides.od,
        odOrigin: overrides.odOrigin,
        odDestination: overrides.odDestination,
        odDI: overrides.odDI || "Dom",
        sector: overrides.sector,
        legDI: overrides.legDI || "Dom",
        identifier: overrides.identifier,
        rowKey: overrides.rowKey || overrides._id,
        odGroupKey: overrides.odGroupKey,
        flightNumber: overrides.flightNumber,
        connectedFlightNumber: overrides.connectedFlightNumber || null,
        flightList: overrides.flightList || [overrides.flightNumber].filter(Boolean),
        timeInclLayover: overrides.timeInclLayover || "00:00",
        pax: overrides.pax,
        cargoT: overrides.cargoT,
        maxPax: overrides.maxPax,
        maxCargoT: overrides.maxCargoT,
        stops: overrides.stops || 0,
        sourceSeats: overrides.sourceSeats || overrides.maxPax,
        sourceCargoCapT: overrides.sourceCargoCapT || overrides.maxCargoT,
        sourcePaxTotal: overrides.sourcePaxTotal || 0,
        sourceCargoTotal: overrides.sourceCargoTotal || 0,
        sourcePaxLF: overrides.sourcePaxLF || 0,
        sourceCargoLF: overrides.sourceCargoLF || 0,
        odViaGcd: overrides.odViaGcd,
        sectorGcd: overrides.sectorGcd,
        totalGcd: overrides.totalGcd || overrides.odViaGcd,
        legFare: 0,
        legRate: 0,
        odFare: 0,
        odRate: 0,
        fareProrateRatioL1L2: 0,
        rateProrateRatioL1L2: 0,
        pooCcyToRccy: 1,
        applySSPricing: false,
    });

    const rows = [
        baseRow({
            _id: "a100-del",
            trafficType: "leg",
            flightId: "A100-2026-03-04",
            poo: "DEL",
            od: "DEL-BOM",
            odOrigin: "DEL",
            odDestination: "BOM",
            sector: "DEL-BOM",
            identifier: "Leg",
            odGroupKey: "leg::A100-2026-03-04",
            flightNumber: "A 100",
            pax: 77,
            cargoT: 0.3,
            maxPax: 153,
            maxCargoT: 0.6,
            odViaGcd: 1200,
            sectorGcd: 1200,
        }),
        baseRow({
            _id: "a100-bom",
            trafficType: "leg",
            flightId: "A100-2026-03-04",
            poo: "BOM",
            od: "DEL-BOM",
            odOrigin: "DEL",
            odDestination: "BOM",
            sector: "DEL-BOM",
            identifier: "Leg",
            odGroupKey: "leg::A100-2026-03-04",
            flightNumber: "A 100",
            pax: 76,
            cargoT: 0.3,
            maxPax: 153,
            maxCargoT: 0.6,
            odViaGcd: 1200,
            sectorGcd: 1200,
        }),
        baseRow({
            _id: "a101-bom",
            trafficType: "leg",
            flightId: "A101-2026-03-04",
            poo: "BOM",
            od: "BOM-HYD",
            odOrigin: "BOM",
            odDestination: "HYD",
            sector: "BOM-HYD",
            identifier: "Leg",
            odGroupKey: "leg::A101-2026-03-04",
            flightNumber: "A 101",
            pax: 64,
            cargoT: 0.7,
            maxPax: 128,
            maxCargoT: 1.4,
            odViaGcd: 600,
            sectorGcd: 600,
        }),
        baseRow({
            _id: "a101-hyd",
            trafficType: "leg",
            flightId: "A101-2026-03-04",
            poo: "HYD",
            od: "BOM-HYD",
            odOrigin: "BOM",
            odDestination: "HYD",
            sector: "BOM-HYD",
            identifier: "Leg",
            odGroupKey: "leg::A101-2026-03-04",
            flightNumber: "A 101",
            pax: 64,
            cargoT: 0.7,
            maxPax: 128,
            maxCargoT: 1.4,
            odViaGcd: 600,
            sectorGcd: 600,
        }),
        baseRow({
            _id: "a102-bom",
            trafficType: "leg",
            flightId: "A102-2026-03-04",
            poo: "BOM",
            od: "BOM-DXB",
            odOrigin: "BOM",
            odDestination: "DXB",
            odDI: "Intl",
            legDI: "Intl",
            sector: "BOM-DXB",
            identifier: "Leg",
            odGroupKey: "leg::A102-2026-03-04",
            flightNumber: "A 102",
            pax: 121,
            cargoT: 3.85,
            maxPax: 243,
            maxCargoT: 7.7,
            odViaGcd: 1900,
            sectorGcd: 1900,
        }),
        baseRow({
            _id: "a102-dxb",
            trafficType: "leg",
            flightId: "A102-2026-03-04",
            poo: "DXB",
            od: "BOM-DXB",
            odOrigin: "BOM",
            odDestination: "DXB",
            odDI: "Intl",
            legDI: "Intl",
            sector: "BOM-DXB",
            identifier: "Leg",
            odGroupKey: "leg::A102-2026-03-04",
            flightNumber: "A 102",
            pax: 122,
            cargoT: 3.85,
            maxPax: 243,
            maxCargoT: 7.7,
            odViaGcd: 1900,
            sectorGcd: 1900,
        }),
        baseRow({
            _id: "del-hyd-behind",
            trafficType: "behind",
            flightId: "A100-2026-03-04",
            connectedFlightId: "A101-2026-03-04",
            poo: "DEL",
            od: "DEL-HYD",
            odOrigin: "DEL",
            odDestination: "HYD",
            sector: "DEL-BOM",
            identifier: "Behind",
            odGroupKey: "system::DEL-HYD::A100-2026-03-04::A101-2026-03-04",
            flightNumber: "A 100",
            connectedFlightNumber: "A 101",
            flightList: ["A 100", "A 101"],
            timeInclLayover: "07:10",
            pax: 0,
            cargoT: 0,
            maxPax: 128,
            maxCargoT: 0.6,
            stops: 1,
            odViaGcd: 1800,
            sectorGcd: 1200,
            totalGcd: 1800,
        }),
        baseRow({
            _id: "del-hyd-beyond",
            trafficType: "beyond",
            flightId: "A101-2026-03-04",
            connectedFlightId: "A100-2026-03-04",
            poo: "DEL",
            od: "DEL-HYD",
            odOrigin: "DEL",
            odDestination: "HYD",
            sector: "BOM-HYD",
            identifier: "Beyond",
            odGroupKey: "system::DEL-HYD::A100-2026-03-04::A101-2026-03-04",
            flightNumber: "A 101",
            connectedFlightNumber: "A 100",
            flightList: ["A 100", "A 101"],
            timeInclLayover: "07:10",
            pax: 0,
            cargoT: 0,
            maxPax: 128,
            maxCargoT: 0.6,
            stops: 1,
            odViaGcd: 1800,
            sectorGcd: 600,
            totalGcd: 1800,
        }),
        baseRow({
            _id: "del-dxb-behind",
            trafficType: "behind",
            flightId: "A100-2026-03-04",
            connectedFlightId: "A102-2026-03-04",
            poo: "DEL",
            od: "DEL-DXB",
            odOrigin: "DEL",
            odDestination: "DXB",
            odDI: "Intl",
            sector: "DEL-BOM",
            identifier: "Behind",
            odGroupKey: "system::DEL-DXB::A100-2026-03-04::A102-2026-03-04",
            flightNumber: "A 100",
            connectedFlightNumber: "A 102",
            flightList: ["A 100", "A 102"],
            timeInclLayover: "09:30",
            pax: 0,
            cargoT: 0,
            maxPax: 153,
            maxCargoT: 0.6,
            stops: 1,
            odViaGcd: 3100,
            sectorGcd: 1200,
            totalGcd: 3100,
        }),
        baseRow({
            _id: "del-dxb-beyond",
            trafficType: "beyond",
            flightId: "A102-2026-03-04",
            connectedFlightId: "A100-2026-03-04",
            poo: "DEL",
            od: "DEL-DXB",
            odOrigin: "DEL",
            odDestination: "DXB",
            odDI: "Intl",
            legDI: "Intl",
            sector: "BOM-DXB",
            identifier: "Beyond",
            odGroupKey: "system::DEL-DXB::A100-2026-03-04::A102-2026-03-04",
            flightNumber: "A 102",
            connectedFlightNumber: "A 100",
            flightList: ["A 100", "A 102"],
            timeInclLayover: "09:30",
            pax: 0,
            cargoT: 0,
            maxPax: 153,
            maxCargoT: 0.6,
            stops: 1,
            odViaGcd: 3100,
            sectorGcd: 1900,
            totalGcd: 3100,
        }),
    ];

    const finalRows = applyTrafficUpdates(rows, [
        { _id: "a100-del", pax: 65, cargoT: 0.1, odFare: 3000, odRate: 45 },
        { _id: "del-hyd-behind", pax: 5, cargoT: 0, odFare: 5000, odRate: 60 },
        { _id: "del-dxb-behind", pax: 12, cargoT: 0.1 },
    ]);

    const byId = new Map(finalRows.map((row) => [row._id, row]));

    assert.equal(byId.get("a100-del").pax, 48);
    assert.equal(byId.get("a100-del").cargoT, 0);
    assert.equal(byId.get("a100-del").odFare, 3000);
    assert.equal(byId.get("a100-del").odRate, 45);

    assert.equal(byId.get("a100-bom").pax, 88);
    assert.equal(byId.get("a100-bom").cargoT, 0.5);
    assert.equal(byId.get("a101-hyd").pax, 59);
    assert.equal(byId.get("a102-dxb").pax, 110);
    assert.equal(byId.get("a102-dxb").cargoT, 3.75);

    assert.equal(byId.get("del-hyd-behind").pax, 5);
    assert.equal(byId.get("del-hyd-beyond").pax, 5);
    assert.equal(byId.get("del-dxb-behind").pax, 12);
    assert.equal(byId.get("del-dxb-beyond").pax, 12);
    assert.equal(byId.get("a101-bom").pax, 64);
    assert.equal(byId.get("a102-bom").pax, 121);
});
